### ISSUE TITLE
Failed to Parse State

### ISSUE THREAD

**Issue by chaosrunner** [captainGeech42/elastic-discord-webhook-proxy#2]
Hello,

I am having issues sending a request from my Kibanna to the proxy, it is able to connect and handle the notifications but failed at the failed to parse state.is trigger bool portion so I am not sure what I am doing wrong. I have used the same body information as per your instructions 

![image](https://user-images.githubusercontent.com/24767759/115714130-c8fc1780-a344-11eb-875a-67942b3a3d64.png)
![image](https://user-images.githubusercontent.com/24767759/115714294-f5b02f00-a344-11eb-887c-d1fde2e8116a.png)

**Comment by captainGeech42** [comment]
Hmm, interesting. That field should be a boolean but maybe that has changed.

A couple requests:

* What version of Kibana is this?
* Can you configure the webhook to point to https://webhook.site/ or something similar, and post the full JSON body?

**Comment by chaosrunner** [comment]
The version of Kibana is 7.12
and when I use configured the webhook to point to the webhook site and posting the JSON body it works without any issues 
![image](https://user-images.githubusercontent.com/24767759/115786552-fa013a00-a38e-11eb-906f-3c0f0468c80d.png)

**Comment by captainGeech42** [comment]
Oh, every field is empty. That will definitely fail it to parse. Probably worth adding a check if the field isn't empty b/f parsing.

Do you get the same error when real data comes from it?

**Comment by chaosrunner** [comment]
How would I go about adding a check for the field? and I may be inputting the data incorrectly, kind of new with elastic search and json so not too sure.

**Comment by captainGeech42** [comment]
Are you clicking a "test alert" button or something in Kibana? I don't remember exactly how that interface works, but that's what I'm assuming is generating those JSON payloads.

If you have some data coming into Elasticsearch, you can configure a test alert that you know will trigger based on the data you have in your environment.

To check the empty fields, I'd add some code [here](https://github.com/captainGeech42/elastic-discord-webhook-proxy/blob/master/main.go#L83) and check if some of the other fields are empty, `alertId` would be a good one that should never be blank on a real alert.

Since this is just test data coming in (I assume), this isn't really a bug, rather a bad error message. You could add an additional error message saying "Fields are blank, assuming test data" or something to that effect.
